post_cb({"bq_ids": {"n4140": {"so_18907605_18907887_1": {"length": 17, "quality": 1.0, "section_id": 986}}, "n3337": {"so_18907605_18907887_1": {"length": 17, "quality": 1.0, "section_id": 971}}, "n4659": {"so_18907605_18907887_1": {"length": 17, "quality": 1.0, "section_id": 1049}}}, "18907605": {"ViewCount": "194", "Body": "<p>I have a class which could potentially throw an exception when constructing.\nI need many objects of this class, and I am constructing them in a vector with emplace_back. What would happen should the constructor throw?</p>\n", "AcceptedAnswerId": "18907887", "Title": "What happens when constructor throws on vector.emplace or vector.emplace_back?", "CreationDate": "2013-09-20T01:35:47.330", "Id": "18907605", "CommentCount": "0", "PostTypeId": "1", "LastActivityDate": "2013-09-20T02:18:32.303", "Score": "3", "OwnerUserId": "1874089", "Tags": "<c++><oop><c++11><stl>", "AnswerCount": "1"}, "18907887": {"Id": "18907887", "PostTypeId": "2", "Body": "<p>It looks like it depends on what constructors are being called.</p>\n<p>According to section 23.3.7.5 in the standard, calls to <code>emplace_back</code> should have no effect if <em>custom</em> constructors throw:</p>\n<blockquote>\n<pre><code>template &lt;class... Args&gt; void emplace_back(Args&amp;&amp;... args);\n</code></pre>\n<p id=\"so_18907605_18907887_0\">[...]</p>\n<p id=\"so_18907605_18907887_1\">If an exception is thrown other than by the copy constructor, move\n  constructor, assignment operator, or move assignment operator of T or\n  by any InputIterator operation there are no effects.</p>\n</blockquote>\n", "LastActivityDate": "2013-09-20T02:18:32.303", "CommentCount": "2", "CreationDate": "2013-09-20T02:18:32.303", "ParentId": "18907605", "Score": "2", "OwnerUserId": "98654"}});